a1=int(input("Enter the number 1\n"))
a2=int(input("Enter the number 2\n"))
a3=int(input("Enter the number 3\n"))
a4=int(input("Enter the number 4\n"))
a5=int(input("Enter the number 5\n"))
a6=int(input("Enter the number 6\n"))
a7=int(input("Enter the number 7\n"))
a8=int(input("Enter the number 8\n"))
s={a1,a2,a3,a4,a5,a6,a7,a8}
print("The unique number is ",s)